/*
 * generated by Xtext
 */
package org.applause.applausedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApplauseDslUiModule extends org.applause.applausedsl.ui.AbstractApplauseDslUiModule {
	public ApplauseDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
