/*
 * generated by Xtext
 */
package org.applause.applausedsl.scoping;

import org.applause.applausedsl.applauseDsl.ObjectReference;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * @see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 */
public class ApplauseDslScopeProvider extends AbstractDeclarativeScopeProvider {
	
	public IScope scope_PropertyPathPart(EObject context, EReference ref) {
		if(context.eContainer() instanceof ObjectReference)
			return new NestedDeclarationScope((ObjectReference) context.eContainer());
		else
			return new PropertyPathPartScope(context);
	}
	

}
