/*
 * generated by Xtext
 */
package org.applause.applausedsl.scoping;

import org.applause.applausedsl.applauseDsl.ObjectReference;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ApplauseDslScopeProvider extends AbstractDeclarativeScopeProvider {
	
	public IScope scope_VariableDeclaration(EObject context, EReference ref) {
		if(context.eContainer() instanceof ObjectReference)
			return new NestedDeclarationScope((ObjectReference) context.eContainer());
		else
			return new VariableDeclarationScope(context);
	}
	

}
